version: "3"

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      # The standard AMQP port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    #networks:
      # - rabbits

  consumer:
    build: consumer
    environment:
      AMQP_URL: "amqp://rabbit-1?connection_attempts=3&retry_delay=3"
    # networks:
    #   - rabbits

  publisher:
    build: publisher
    environment:
      AMQP_URL: "amqp://rabbit-1?connection_attempts=3&retry_delay=3"
    # networks:
    #   - rabbits

networks:
  # Declare our private network.
  default:
    driver: bridge